services:
  katalog-service:
    build: .
    container_name: katalog_service
    ports:
      - "3003:3003"
    env_file:
      - .env

  katalog-db:
    image: mysql:8
    container_name: katalog_db
    restart: always
    environment:
      MYSQL_DATABASE: katalog_db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3309:3306"