services:
  user-service:
    build: .
    container_name: user_service
    ports:
      - "3001:3001"
    env_file:
      - .env

  user-db:
    image: mysql:8
    container_name: user_db
    restart: always
    environment:
      MYSQL_DATABASE: user_db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"